### ISSUE TITLE
iOS Support and acr1255u

### ISSUE THREAD

**Issue by EbramTawfik** [ijazfx/acs-nfc-reader#1]
I am trying to use the package but I have some question:
1- Does it support iOS?
2- Is there a way to use it with acr1255u? and if there documentation?
https://www.acs.com.hk/en/products/528/acr1255u-j1-acs-secure-bluetooth%C2%AE-nfc-reader-software-development-kit/

**Comment by ijazfx** [comment]
1. No it does not support iOS out of the box. I've used acssmc-1.1.5.jar which is available in android's libs folder. I had a very specific Kiosk requirement so used only for that purpose.
2. It should work as the jar file used in EVK for both 122u and 1252u is same. I didn't see a variant with 1255u but you may try.

https://www.acs.com.hk/en/driver/342/acr1252u-usb-nfc-reader-iii-nfc-forum-certified-reader/

Usage is simple. Refer the package in your application using "path:" property where path points to acs-nfc-reader folder. Use the code as follows:

> AcsNfcReader.initialize();
    AcsNfcReader.onScan((MethodCall call) {
      var data = HEX.decode(call.arguments);
      // This is the data detected from the card. It gives you raw data, does not support NDEF format but you can play with the code in acs-nfc-reader to make it work for you.
    });

My case is specific but you can get an idea. You will receive the data in HEX encoded format as "call.arguments". Decode the data and use the way you want.

**Comment by EbramTawfik** [comment]
Ok thanks. so it doesn't support Bluetooth scanning for 1255u device right?

will it be easy adding the support to the package using code similar to : 
iOS:
https://github.com/MartinPham/cordova-plugin-bluetooth-nfc/tree/master/src/ios

Android:
https://github.com/MartinPham/cordova-plugin-bluetooth-nfc/blob/master/src/android/BluetoothNFC.java
